
name: Create a new release

on: 
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Select the version type: (major|minor|patch)'     
        required: true
        default: 'patch'
  
jobs:
  release:
    if: github.event.inputs.versionType == 'patch' || github.event.inputs.versionType == 'minor' || github.event.inputs.versionType == 'major'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set release user
        run: git config  user.email "work@maikpaulus.com" && git config --global user.name "Maik Paulus"

      - name: Save new version to env variable
        run: echo ::set-env name=RELEASE_VERSION::$(cat package.json | grep version | sed 's/[^.0-9]//g')

      - name: Set a new version with NPM
        run: npm version ${{ github.event.inputs.versionType }} -m "[release] Bumped version from ${RELEASE_VERSION} to %s"

      - name: Push new version to repository
        run: git push origin master && git push --tags

      - name: Save new version to env variable
        run: echo ::set-env name=RELEASE_VERSION::$(cat package.json | grep version | sed 's/[^.0-9]//g')